# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'debug', '>= 1.0'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'simplecov', '~> 0.22'
  gem 'vcr', '~> 6.1'
  gem 'webmock', '~> 3.18'
  gem 'yard', '~> 0.9'
end
