# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'yard'

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new
YARD::Rake::YardocTask.new

task default: %i[rubocop spec]

namespace :coverage do
  desc 'Open coverage report'
  task :open do
    system 'open coverage/index.html'
  end
end
